version: '3.9'
services:
  location-service:
    image: elaina/location
    container_name: location-container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      # - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./..:/home/Elaina/location
    network_mode: host
    pid: "host"
    ipc: "host"
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina"
    runtime: "nvidia"
    working_dir: "/home/Elaina/location"
    # profiles:
    # - build-required

  builder:
    build:
      context: .
    image: elaina/location
    profiles:
      - build-required
